import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Helper Buddy",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/helperbuddy-logo.ico" },
    ],
  }
};
